version: '3.1'

services: 

  cache: 
    
    image: redis:6.0.9
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    container_name: zhuomiredis
    ports: 
      - "6379:6379"
    volumes: 
      - "./conf:/usr/local/etc/redis"
      - "./datas:/data"
    
    








